version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup QEMU
          command: docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - run:
          name: Dagger Test Pipeline
          command: go run ci/main.go test
      - run:
          name: Test results
          command: tail -n +1 output/*/*/*.out
workflows:
  test:
    jobs:
      - test
