version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup Engine
          command: |
            docker run \
            --name dagger-engine \
            --privileged \
            -e _EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN=$CACHE_TOKEN \
            -v dagger-engine:/var/lib/dagger \
            registry.dagger.io/engine:v0.6.2
      - run:
          name: Dagger Test Pipeline
          command: go run ./ci ci
      - run:
          name: Test results
          command: tail -n +1 output/*/*/*.out
workflows:
  test:
    jobs:
      - test
