baseURL = 'https://greetings.kylepenfound.com/'
languageCode = 'en-us'
title = 'Greetings Website'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
[Params]
    backend = 'http://localhost:8080'
