# fly.toml app configuration file generated for dagger-demo on 2023-10-30T17:43:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dagger-demo"
primary_region = "ord"

[build]
  image = "ttl.sh/greetings-api:1h@sha256:0d67511b454b51484c92a6b35061cc539e4279bd4802a493cdaff8d3a58eea07"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
