name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v3
      - run: |
          go run ci/main.go ci
