name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v3
      - run: |
          export _EXPERIMENTAL_DAGGER_RUNNER_HOST="unix:///var/run/buildkit/buildkitd.sock"
          DAGGER_CLI_COMMIT="f2a62f276d36918b0e453389dc7c63cad195da59"
          DAGGER_TMP_BINDIR="/tmp/dagger_${DAGGER_CLI_COMMIT}"
          export _EXPERIMENTAL_DAGGER_CLI_BIN="$DAGGER_TMP_BINDIR/dagger"
          if [ ! -f  "$_EXPERIMENTAL_DAGGER_CLI_BIN" ]; then
            mkdir -p "$DAGGER_TMP_BINDIR"
            curl "https://dl.dagger.io/dagger/main/${DAGGER_CLI_COMMIT}/dagger_${DAGGER_CLI_COMMIT}_$(uname -s | tr A-Z a-z)_$(uname -m | sed s/x86_64/amd64/).tar.gz" | tar xvz -C "$DAGGER_TMP_BINDIR"
          fi
          ${_EXPERIMENTAL_DAGGER_CLI_BIN} run --debug go run ci/main.go ci
